{% set name = "ml-research" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ml_research-{{ version }}.tar.gz
  sha256: 0af6523764a185eca293ff4cc9050ead8136f45a801375bb6fa7dbd399780354

build:
  # noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools
  run:
    - python >=3.11
    - numpy >=1.14
    - pandas >=1.3.5
    - imbalanced-learn >=0.8.0
    - matplotlib-base
    - requests
    - rich
    - scikit-learn >=1.0.0

test:
  imports:
    - mlresearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joaopfonseca/ml-research
  summary: Implementation of Machine Learning algorithms, experiments and utilities.
  license: MIT
  license_file: LICENSE
  doc_url: https://mlresearch.readthedocs.io

extra:
  recipe-maintainers:
    - joaopfonseca
